//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Experimentos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuestionario
    {
        public int id_cuestionario { get; set; }
        public int id_participante { get; set; }
        public int id_preguntas { get; set; }
        public string p1 { get; set; }
        public string p2 { get; set; }
        public string p3 { get; set; }
        public string p4 { get; set; }
        public string p5 { get; set; }
        public string p6 { get; set; }
        public string p7 { get; set; }
        public string p8 { get; set; }
    
        public virtual pregunta pregunta { get; set; }
        public virtual participante participante { get; set; }
    }
}
