//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Experimentos.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Experiments_App_Entities : DbContext
    {
        public Experiments_App_Entities()
            : base("name=Experiments_App_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cuestionario> cuestionarios { get; set; }
        public virtual DbSet<participante> participantes { get; set; }
        public virtual DbSet<pregunta> preguntas { get; set; }
        public virtual DbSet<eyeData> eyeDatas { get; set; }
        public virtual DbSet<respuestasExperimento> respuestasExperimentos { get; set; }
    }
}
