//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Experimentos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class participante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public participante()
        {
            this.cuestionarios = new HashSet<cuestionario>();
            this.eyeDatas = new HashSet<eyeData>();
            this.respuestasExperimentos = new HashSet<respuestasExperimento>();
        }
    
        public int id_participante { get; set; }
        public Nullable<int> edad { get; set; }
        public string sexo { get; set; }
        public string semestre { get; set; }
        public string nivel { get; set; }
        public Nullable<int> cuestionario { get; set; }
        public string lentes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cuestionario> cuestionarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eyeData> eyeDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<respuestasExperimento> respuestasExperimentos { get; set; }
    }
}
